# Generated by Django 3.0.8 on 2020-07-20 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_topic_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='replies',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
